spring.application.name=ledger-service

# This tells Hibernate to automatically create the tables based on your Java classes
spring.jpa.hibernate.ddl-auto=update

# This shows the SQL in the console so you can see the table being created
spring.jpa.show-sql=true

# Important: Ensures Postgres naming conventions match Spring (snake_case)
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl